name: "land"
services:
  rails:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/rails:cached
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:17.5
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  vite:
    image: node:24-slim
    working_dir: /vite
    volumes:
      - ./frontend:/vite
    command: sh -c "npm i; npm run dev"
    ports:
      - "5173:5173"