// DO NOT EDIT! This file is automatically generated.
import request from './request'

export type Space = {name: string, note: string, path: string}

export default {
  spaces: {
    show(params: {id: number}): Promise<{space: Space}>{ return request('get', '/spaces/show', params) },
  },
}
